name = "hugo-theme-console-dark"
license = "MIT"
licenselink = "https://github.com/zx1239856/hugo-theme-console-dark/blob/master/LICENSE"
description = "A minimal, responsive and light theme for Hugo inspired by Linux console. Added dark mode support"
homepage = "https://github.com/zx1239856/hugo-theme-console-dark"
tags = ["blog", "gallery", "portfolio", "console", "terminal", "clean", "personal", "minimal", "monotone", "simple", "technical", "responsive", "mobile", "minimalist", "retro", "animation", "dark"]
features = ["disqus", "responsive", "google analytics", "dark mode"]
min_version = "0.81.0"

[author]
    name = "Xiang Zhang"
    homepage = "https://xzhang.dev"
    github = "https://github.com/zx1239856"

[original]
    author = "Marcin Mierzejewski"
    homepage = "https://mrmierzejewski.com"
    repo = "https://github.com/mrmierzejewski"
